apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: my-demo-app
description: main application pipeline
serialPipeline:
 stages:
 - targetId: atson-corp-gke
   profiles: []
---


apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: atson-corp-gke
description: production cluster
gke:
 cluster: projects/gke-demo-398306/locations/us-central1/clusters/atson-corp-cluster
